### ISSUE TITLE
After last commit, toJson throws exception

### ISSUE THREAD

**Issue by Dauthjan** [tomlj/tomlj#12]
Hi @cleishm 
After the last commit, I'm facing issue with toJson(). Here's what I did:

**_TOML:_**

```
[[fruit]]
name = "apple"

[[fruit.physical]]
color = "red"
shape = "round"

[[fruit.variety]]
name = "red delicious"

[[fruit.variety]]
  name = "granny smith"

[[fruit]]
name = "banana"

[[fruit.variety]]
name = "plantain"
```

**_Code:_**

```Java
Path   TOML = Paths.get("D:/test/test.toml");
TomlParseResult toml = Toml.parse(TOML);
String result = toml.toJson();
System.out.println(result);
```

**_Exception:_**

```Java
java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(Unknown Source)
	at org.tomlj.JsonSerializer.toJson(JsonSerializer.java:73)
	at org.tomlj.JsonSerializer.appendTomlValue(JsonSerializer.java:110)
	at org.tomlj.JsonSerializer.toJson(JsonSerializer.java:46)
	at org.tomlj.JsonSerializer.toJson(JsonSerializer.java:30)
	at org.tomlj.TomlTable.toJson(TomlTable.java:1240)
	at org.tomlj.TomlTable.toJson(TomlTable.java:1225)
	at Main.main(Main.java:29)
```

**Comment by Dauthjan** [comment]
_Just to add up a note:_ before this change, it was working fine for the same TOML.
**_Expected result_**

```JSON
{
  "fruit": [{
      "name": "apple",
      "physical": {
        "color": "red",
        "shape": "round"
      },
      "variety": [{
          "name": "red delicious"
        },{
          "name": "granny smith"
        }]
    },{
      "name": "banana",
      "variety": [{
          "name": "plantain"
        }]
    }]
}
```
