### ISSUE TITLE
Getting tables with spaces in their key doesn't seem to work

### ISSUE THREAD

**Issue by nguillaumin** [tomlj/tomlj#2]
Given the following TOML:

```toml
[columns]

    [columns."Website 1"]
        module = "Person"
        target = "group"
        group = "PerContactGrp"
        field = "ValueTxt"
        qualifier = 1
```

Trying to do:

```groovy
def toml = Toml.parse(tomlFile.toPath())
println toml.getTable("columns").getTable("Website 1").keySet()
```

Throws an error:
```java
java.lang.IllegalArgumentException: Invalid key: Unexpected '1', expected end-of-input
	at org.tomlj.Parser.parseDottedKey(Parser.java:96)
	at org.tomlj.TomlTable.getTable(TomlTable.java:1085)
Caused by: Unexpected '1', expected end-of-input (line 1, column 9)
	at org.tomlj.AccumulatingErrorListener.reportError(AccumulatingErrorListener.java:67)
	at org.tomlj.AccumulatingErrorListener.syntaxError(AccumulatingErrorListener.java:54)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportUnwantedToken(DefaultErrorStrategy.java:377)
	at org.antlr.v4.runtime.DefaultErrorStrategy.singleTokenDeletion(DefaultErrorStrategy.java:548)
	at org.antlr.v4.runtime.DefaultErrorStrategy.recoverInline(DefaultErrorStrategy.java:467)
	at org.antlr.v4.runtime.Parser.match(Parser.java:206)
	at org.tomlj.internal.TomlParser.tomlKey(TomlParser.java:357)
	at org.tomlj.Parser.parseDottedKey(Parser.java:92)
	... 3 more
```

If I remove the space in the table name (i.e. "Website1"), it works.

**Comment by Dauthjan** [comment]
@nguillaumin 
Try System.out.println(result.getTable("columns").getTable("\"Website 1\"").keySet());

**Comment by Dauthjan** [comment]
Tried this?
`System.out.println(toml.getTable("columns").getTable("\"Website 1\"").keySet());`

**Comment by cleishm** [comment]
Feel free to issue a pull request, including a test case!

**Comment by cleishm** [comment]
This is an interesting issue - on review, the current behavior is correct and as intended. The argument to those methods is a dotted key, and dotted keys _must_ include quotes around anything that contains spaces. E.g. `columns."Website 1"`.

However, I do see the usability issue here. Given the usage context (i.e. _only for parsing these arguments), I think we can actually alter the parsing grammar to allow unquoted keys within the dot sequence. E.g. allow `Website 1` and even `columns.Website 1`.

While this would create ambiguities in the grammar if allowed in a TOML document, in this context it should be ok.
