### ISSUE TITLE
Datetime array issues

### ISSUE THREAD

**Issue by Dauthjan** [tomlj/tomlj#4]
**_Case 1 :-_**

_Code:_ 
```
	public static void main(String[] args) {

		TomlParseResult toml = null;
		try {
			Path source = Paths.get("D:/test/example.toml");
			toml = Toml.parse(source);
			TomlArray array = toml.getTable("array").getArray("key1");
			System.out.println("Count: " + array.size());
			for (int i = 0; i < array.size(); i++) {
				System.out.println("Value " + (i+1) + ": " + array.get(i));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
```

_Data:_
```
[array]
key1 = [1979-05-27T00:32:00.999999-07:00, 1979-05-28T00:32:00.999999-07:00, 1979-05-31T07:32:00]
```
    
_Result:_
```
Count: 2
Value 1: 1979-05-27T00:32:00.999999-07:00
Value 2: 1979-05-28T00:32:00.999999-07:00
```

**Debug shows error: "Unexpected '1979-05-31T07', expected ] or a newline" But no exception thrown.
Expected: Successful Execution**

Got the below stacktrace:
```
java.lang.IllegalArgumentException: Error occured during parsing: Unexpected ']', expected ], a comma, or a newline
	at org.tomlj.Parser.parse(Parser.java:41)
	at org.tomlj.Toml.parse(Toml.java:80)
	at org.tomlj.Toml.parse(Toml.java:67)
	at Main.main(Main.java:16)
Caused by: Unexpected ']', expected ], a comma, or a newline (line 188, column 102)
	at org.tomlj.AccumulatingErrorListener.reportError(AccumulatingErrorListener.java:67)
	at org.tomlj.AccumulatingErrorListener.syntaxError(AccumulatingErrorListener.java:54)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportUnwantedToken(DefaultErrorStrategy.java:377)
	at org.antlr.v4.runtime.DefaultErrorStrategy.singleTokenDeletion(DefaultErrorStrategy.java:548)
	at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:266)
	at org.tomlj.internal.TomlParser.array(TomlParser.java:3011)
	at org.tomlj.internal.TomlParser.val(TomlParser.java:754)
	at org.tomlj.internal.TomlParser.keyval(TomlParser.java:409)
	at org.tomlj.internal.TomlParser.expression(TomlParser.java:298)
	at org.tomlj.internal.TomlParser.toml(TomlParser.java:219)
	at org.tomlj.Parser.parse(Parser.java:37)
	... 3 more

```

**_Case 2 :-_**  -  **UPDATE: I understood how error handling is done. Consider Case 2 as SOLVED!**

_Code:_ Same as Case 1

_Data:_
```
[array]
key1 = [s1979-05-27T00:32:00.999999-07:00, s1979-05-28T00:32:00.999999-07:00, s1979-05-31T07:32:00]
```

_Result:_
```
Count: 1
Value 1: 1979-05-27T00:32:00.999999-07:00
```

**Expected: ParserException**

**_Case 3 :-_**

_Code:_
```
	public static void main(String[] args) {

		TomlParseResult toml = null;
		try {
			Path source = Paths.get("D:/test/example-v0.4.0.toml");
			toml = Toml.parse(source);
			TomlArray array = toml.getTable("array").getArray("key1");
			System.out.println("Count: " + array.size());
			System.out.println(array.containsLongs());
			System.out.println(array.containsStrings());
			System.out.println(array.containsBooleans());
			System.out.println(array.containsOffsetDateTimes());
			System.out.println(array.containsLocalDateTimes());
			System.out.println(array.containsLocalDates());
			System.out.println(array.containsLocalTimes());
			System.out.println(array.containsDoubles());
			for (int i = 0; i < array.size(); i++) {
				System.out.println("Value " + (i+1) + ": " + array.get(i));// + " -> " + TomlType.typeNameFor(array.get(i)));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
```

_Data:_
```
[array]
key1 = [s1979-0x5-27T00:32:00.999999-07:00, s1979-05-28T00:32:00.999999-07:00, s1979-05-31T07:32:00]
```

_Result:_
```
Count: 0
true
true
true
true
true
true
true
true
```

**Expected: ParserException. Boolean values to be false?**

Can you please have a look? 
Also, #3 was raised by me. I tweaked the source a bit and they seem to work as expected. 
Can you please have a look at #3  and make/merge necessary changes?

Again, thank you for this lib! I'm not a java developer, nor an expert in Java. Found TOML and decided to play with it. If you get time, please take the below requests into consideration:

**_Requests:_**

**(i)** The reason I asked for maintaining sequence while creating JSON - want to implement JSON schema validation on this. In future, may be [TOLS](https://github.com/toml-lang/toml/pull/116) would be reality to validate the structure!
**(ii)** How about a toToml() similar to toJson()? Converts JSON to TOML.

Hope to see v1.0 implemented as well 👍

**Comment by cleishm** [comment]
Please send a PR with a test case!

**Comment by Dauthjan** [comment]
Hi @cleishm Thanks for noticing my concern. I've [forked ](https://github.com/Dauthjan/tomlj) tomlj.
Although I'm not at all comfortable with java, (I'm [IBM IIB](https://en.wikipedia.org/wiki/IBM_Integration_Bus) Developer mostly working on [Extended SQL](https://www.ibm.com/support/knowledgecenter/SSMKHH_10.0.0/com.ibm.etools.mft.doc/ak00990_.html)), I've tried to address issues from #1 , #2  and #3 [here](https://github.com/Dauthjan/tomlj). Additionally, I added JSON validation, hence `toJson()` should throw a `JSONException` if invalid JSON is created. Additional to this, I introduced a new method `toJsonPath()` which gives a Map of `<JSONPath, value>`. I noticed `toMap()` doesn't drill down deep in data types. Although these changes were tested manually by me, there's no test cases as of now.

While I'll be informing about bugs (_if I find any_), one issue in particular that I couldn't figure out is **_Case 1_** from this above raised issue.

**Code:**
```
Path source = Paths.get("D:/test/example-v0.4.0.toml");
toml = Toml.parse(source);
System.out.println(toml.getTable("array").getArray("key5").toList());;
```
**_Data:_**
```
[array]
key5 = [1993-08-04, 1993-08-04, 1993-08-04, 1993-08-04]
```
**_StackTrace_**
```
java.lang.IllegalArgumentException: A parsing error has occured: Unexpected '1993-08-04', expected ] or a newline
	at org.tomlj.Parser.parse(Parser.java:42)
	at org.tomlj.Toml.parse(Toml.java:130)
	at org.tomlj.Toml.parse(Toml.java:103)
	at Main.main(Main.java:17)
Caused by: Unexpected '1993-08-04', expected ] or a newline (line 2, column 33)
	at org.tomlj.AccumulatingErrorListener.reportError(AccumulatingErrorListener.java:67)
	at org.tomlj.AccumulatingErrorListener.syntaxError(AccumulatingErrorListener.java:48)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
	at org.tomlj.internal.TomlParser.array(TomlParser.java:3043)
	at org.tomlj.internal.TomlParser.val(TomlParser.java:754)
	at org.tomlj.internal.TomlParser.keyval(TomlParser.java:409)
	at org.tomlj.internal.TomlParser.expression(TomlParser.java:298)
	at org.tomlj.internal.TomlParser.toml(TomlParser.java:219)
	at org.tomlj.Parser.parse(Parser.java:37)
	... 3 more
```

I noticed `TomlParser.java` throwing error at around line `218/219`. I tried same operation with integers and characters in array but none of them throwing error. I hope to get some help on this. Thanks a lot in advance!

**Comment by cleishm** [comment]
You can follow these instructions to submit a pull request: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by Dauthjan** [comment]
Hi @cleishm  here's the [PR](https://github.com/tomlj/tomlj/pull/5) I've tried describing my work till now

**Comment by Dauthjan** [comment]
I've tried the test with exact same data as well. 

TOML: 
`key1 = [ 1993-08-04T15:05:00Z, 1993-08-04T15:05:00Z, 1993-08-04T15:05:00Z, 1993-08-04T15:05:00Z ]`

Expected Result:
```
{
    "key1": [
        "1993-08-04T15:05:00Z",
        "1993-08-04T15:05:00Z",
        "1993-08-04T15:05:00Z",
        "1993-08-04T15:05:00Z"
    ]
}
```
Exception: 
```Java
java.lang.IllegalArgumentException: A parsing error has occured: Unexpected '1993-08-04T15', expected ] or a newline
	at org.tomlj.Parser.parse(Parser.java:43)
	at org.tomlj.Toml.parse(Toml.java:80)
	at org.tomlj.Toml.parse(Toml.java:55)
	at Main.main(Main.java:14)
Caused by: Unexpected '1993-08-04T15', expected ] or a newline (line 1, column 54)
	at org.tomlj.AccumulatingErrorListener.reportError(AccumulatingErrorListener.java:67)
	at org.tomlj.AccumulatingErrorListener.syntaxError(AccumulatingErrorListener.java:48)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:510)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
	at org.tomlj.internal.TomlParser.array(TomlParser.java:3043)
	at org.tomlj.internal.TomlParser.val(TomlParser.java:754)
	at org.tomlj.internal.TomlParser.keyval(TomlParser.java:409)
	at org.tomlj.internal.TomlParser.expression(TomlParser.java:298)
	at org.tomlj.internal.TomlParser.toml(TomlParser.java:196)
	at org.tomlj.Parser.parse(Parser.java:38)
	... 3 more
```

**Comment by Dauthjan** [comment]
> The problem is that you're adding different types to the array.

I've tweaked the source code a bit to allow heterogeneous values in arrays (standardized in [v1.0.0-rc.1](https://github.com/toml-lang/toml/blob/master/CHANGELOG.md#100-rc1--2020-04-01))

It still throws error. `A parsing error has occured: Unexpected ']', expected ], a comma, or a newline`

**Comment by cleishm** [comment]
Ah, so this is a new requirement for toml v1.0, which this library doesn't support (yet).

However, there's certainly an issue with that parse error `Unexpected ']', expected ]`.

**Comment by Dauthjan** [comment]
Hi @cleishm 
I'm not focusing on the heterogeneous values for now....
That can be focused later... I've added some test cases which might be helpful for you?
This error is pops up only if I add more than two offset Datetime or local datetime or date or time... 
Didn't face such issue with float or int or char

**Comment by cleishm** [comment]
Yes, figured it out. PR incoming.

**Comment by Dauthjan** [comment]
Amazing!!
