### ISSUE TITLE
java.lang.StackOverflowError: stack size 1039KB

### ISSUE THREAD

**Issue by disert** [tomlj/tomlj#41]
hi,I met a problem,when toml file is too big! 
`
java.lang.StackOverflowError: stack size 1039KB
	at java.util.stream.Sink$ChainedReference.<init>(Sink.java:250)
	at java.util.stream.SortedOps$AbstractRefSortingSink.<init>(SortedOps.java:310)
	at java.util.stream.SortedOps$SizedRefSortingSink.<init>(SortedOps.java:335)
	at java.util.stream.SortedOps$OfRef.opWrapSink(SortedOps.java:141)
	at java.util.stream.AbstractPipeline.wrapSink(AbstractPipeline.java:523)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.initPartialTraversalState(StreamSpliterators.java:293)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:158)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at org.tomlj.JsonSerializer.toJson(JsonSerializer.java:39)
	at org.tomlj.JsonSerializer.appendTomlValue(JsonSerializer.java:112)
	at org.tomlj.JsonSerializer.toJson(JsonSerializer.java:44)
        ...
        at org.tomlj.JsonSerializer.toJson(JsonSerializer.java:29)
	at org.tomlj.TomlTable.toJson(TomlTable.java:1173)
	at org.tomlj.TomlTable.toJson(TomlTable.java:1158)
	
	
	//my code:
	
	 Path source = Paths.get(tomlPath);
        TomlParseResult result = null;
        try {
            result = Toml.parse(source);
        } catch (IOException e) {
            LogUtils.e(e.getMessage());
            addLoadErrorMsg("parse toml fial: "+e.getMessage());
            throw new TomlParseException(e.getMessage());
        }
        return result.toJson();
`
I,m want to fix it

**Comment by lkishalmi** [comment]
It would have been much more useful to provide the TOML Source that'd cause the parser go most probably into infinite recursion.

**Comment by cleishm** [comment]
Without the source that causes the issue, there is not much we can do here.
